import React from "react";
import {
    AlertTriangle,
    AudioLines,
    Check,
    Clock,
    Crop,
    Download,
    Eye,
    EyeOff,
    FileText,
    Headphones,
    Image as ImageIcon,
    Loader2,
    Lock,
    LockOpen,
    Magnet,
    Merge,
    Mic,
    Minus,
    MoreVertical,
    Music,
    Pause,
    Play,
    Plus,
    Redo2,
    RefreshCw,
    Scissors,
    Target,
    Trash2,
    Undo2,
    Video,
    Volume2,
    VolumeX,
    X,
} from "lucide-react";

const ICONS = {
    "alert-triangle": AlertTriangle,
    "audio-lines": AudioLines,
    check: Check,
    clock: Clock,
    crop: Crop,
    download: Download,
    eye: Eye,
    "eye-off": EyeOff,
    "file-text": FileText,
    headphones: Headphones,
    photo: ImageIcon,
    loader: Loader2,
    lock: Lock,
    "lock-open": LockOpen,
    magnet: Magnet,
    merge: Merge,
    microphone: Mic,
    minus: Minus,
    "dots-vertical": MoreVertical,
    music: Music,
    "player-pause": Pause,
    "player-play": Play,
    plus: Plus,
    redo: Redo2,
    refresh: RefreshCw,
    scissors: Scissors,
    target: Target,
    trash: Trash2,
    undo: Undo2,
    video: Video,
    volume: Volume2,
    "volume-off": VolumeX,
    x: X,
};

export default function Icon({ name, size = 16, className = "", ...props }) {
    const Cmp = ICONS[name] || AlertTriangle;
    return <Cmp size={size} className={className} aria-hidden {...props} />;
}
